#!/usr/bin/env bash
# generate-stubs.sh <pack-dir> -- render verb stubs from pack/stubs.jsonc
# and the zone's mattstack.jsonc marker. Generated files carry a header;
# files without it are never overwritten.
set -euo pipefail
PACK_DIR=$(cd "${1:?usage: generate-stubs.sh <pack-dir>}" && pwd)
strip() { sed 's|^[[:space:]]*//.*$||' "$1"; }
d=$PACK_DIR; MARKER=""
while [ "$d" != "/" ]; do
  [ -f "$d/mattstack.jsonc" ] && { MARKER="$d/mattstack.jsonc"; break; }
  d=$(dirname "$d")
done
[ -n "$MARKER" ] || { echo "no mattstack.jsonc found above $PACK_DIR" >&2; exit 1; }
NS=$(strip "$MARKER" | jq -r '.namespace // empty')
[ -n "$NS" ] || { echo "marker $MARKER has no namespace" >&2; exit 1; }
STUBS="$PACK_DIR/pack/stubs.jsonc"
[ -f "$STUBS" ] || { echo "no pack/stubs.jsonc in $PACK_DIR" >&2; exit 1; }
HEADER="<!-- generated by generate-stubs.sh; DO NOT hand-edit: regeneration overwrites this file. Edit pack/stubs.jsonc and regenerate. -->"
strip "$STUBS" | jq -r '.verbs | to_entries[] | [.key, .value.engine, .value.description] | @tsv' |
while IFS=$'\t' read -r VERB ENGINE DESC; do
  OUT="$PACK_DIR/skills/$VERB/SKILL.md"
  if [ -f "$OUT" ] && ! grep -qF "$HEADER" "$OUT"; then
    echo "refusing to overwrite non-generated $OUT" >&2; exit 1
  fi
  mkdir -p "$PACK_DIR/skills/$VERB"
  {
    printf -- '---\nname: %s\ndescription: "%s"\n---\n%s\n\n' "$VERB" "$DESC" "$HEADER"
    printf '# %s:%s\n\n' "$NS" "$VERB"
    printf 'You are the %s entry for this verb. Invoke the skill\n' "$NS"
    printf '`mattstack:%s` now and follow it end to end; bindings resolve\n' "$ENGINE"
    printf 'from the manifest as usual. Relay the provenance line it prints.\n'
  } > "$OUT"
  echo "wrote $OUT"
done
