#!/usr/bin/env bash
# merge-manifests.sh [--repo <path>] -- write the per-repo bindings manifest
# from team-zone fragments plus the user zone's overrides. Layers and rules:
# references/convention.md, "Manifest layers".
set -euo pipefail
REPO=$PWD
if [ "${1:-}" = "--repo" ]; then REPO=$(cd "${2:?--repo needs a path}" && pwd); fi
MS_HOME="${MATTSTACK_HOME:-$HOME/.mattstack}"
strip() { sed 's|^[[:space:]]*//.*$||' "$1"; }

norm_url() { # url -> host/path (no protocol, creds, .git; host lowercased)
  local u=$1
  u=${u%.git}
  u=${u#ssh://}; u=${u#https://}; u=${u#http://}; u=${u#git://}
  u=${u#*@}
  u=${u/:/\/}
  local host=${u%%/*} path=${u#*/}
  printf '%s/%s' "$(printf %s "$host" | tr 'A-Z' 'a-z')" "$path"
}

REMOTE=$(git -C "$REPO" remote get-url origin 2>/dev/null || true)
if [ -z "$REMOTE" ]; then
  FIRST=$(git -C "$REPO" remote 2>/dev/null | head -1 || true)
  [ -n "$FIRST" ] && REMOTE=$(git -C "$REPO" remote get-url "$FIRST" 2>/dev/null || true)
fi
[ -n "$REMOTE" ] || { echo "merge-manifests: no git remote in $REPO -- no per-repo manifest" >&2; exit 2; }
# Known limitation: an explicit port (ssh://host:2222/path) stays in the
# slug; both writer and readers share this, so they agree.
NORM=$(norm_url "$REMOTE"); HOST=${NORM%%/*}; RPATH=${NORM#*/}
SLUG="$HOST-$(printf %s "$RPATH" | tr '/' '-')"

# Collect fragments from every declaring team zone.
FRAGS_JSON=$(mktemp "${TMPDIR:-/tmp}/merge-frags.XXXXXX")
trap 'rm -f "$FRAGS_JSON"' EXIT
printf '[]' > "$FRAGS_JSON"
add_frag() { # $1=src-label $2=fragment-path
  local tmp
  tmp=$(strip "$2" | jq -c --arg src "$1" '{src: $src, data: .}') || {
    echo "merge-manifests: fragment is not valid JSONC: $2" >&2; exit 1; }
  jq -c --argjson f "$tmp" '. + [$f]' "$FRAGS_JSON" > "$FRAGS_JSON.n" && mv "$FRAGS_JSON.n" "$FRAGS_JSON"
}

shopt -s nullglob
for CLONE in "$MS_HOME"/teams/*/; do
  MARKERS=$( (cd "$CLONE" && git ls-files 2>/dev/null | grep -E '(^|/)mattstack\.jsonc$') || \
             (cd "$CLONE" && find . -name mattstack.jsonc | sed 's|^\./||') )
  for M in $MARKERS; do
    ZONE=$(dirname "$CLONE$M")
    ROLE=$(strip "$ZONE/mattstack.jsonc" | jq -r '.role // empty')
    [ "$ROLE" = "team" ] || continue
    NS=$(strip "$ZONE/mattstack.jsonc" | jq -r '.namespace // empty')
    [ -f "$ZONE/team.jsonc" ] || continue
    THOST=$(strip "$ZONE/team.jsonc" | jq -r '.gitlabHost // empty')
    THOST=${THOST#https://}; THOST=${THOST#http://}; THOST=${THOST%%/*}
    THOST=$(printf %s "$THOST" | tr 'A-Z' 'a-z')
    [ "$THOST" = "$HOST" ] || continue
    strip "$ZONE/team.jsonc" | jq -e --arg p "$RPATH" '.projects | index($p) != null' > /dev/null || continue
    for FRAG in "$ZONE"/packs/*/pack/skills.jsonc; do
      add_frag "$NS@$(basename "$CLONE")" "$FRAG"
    done
  done
done

DECLARED=$(jq 'length' "$FRAGS_JSON")
[ "$DECLARED" -gt 0 ] || { echo "merge-manifests: no team declares $NORM -- no per-repo manifest" >&2; exit 2; }

OVR="$MS_HOME/user/skills/overrides.jsonc"
[ -f "$OVR" ] && add_frag "user-override" "$OVR"

MERGED=$(jq -c '
  reduce .[] as $f (
    {enabled: [], pipelines: {}, bindings: {}, prov: {}, conflicts: []};
    ($f.src | startswith("user-override")) as $ovr
    | .enabled += ($f.data.skills.enabled // [])
    | reduce (($f.data.pipelines // {}) | to_entries[]) as $p (.;
        if (.pipelines[$p.key] != null) and (.pipelines[$p.key] != $p.value) and ($ovr | not)
        then .conflicts += ["pipeline \($p.key): \(.prov["pipeline " + $p.key]) vs \($f.src)"]
        else .pipelines[$p.key] = $p.value | .prov["pipeline " + $p.key] = $f.src end)
    | reduce (($f.data.bindings // {}) | to_entries[]) as $b (.;
        reduce ($b.value | to_entries[]) as $s (.;
          (.bindings[$b.key][$s.key]) as $cur
          | if ($cur != null) and ($cur != $s.value) and ($ovr | not)
            then .conflicts += ["\($b.key) slot \($s.key): \($cur) from \(.prov[$b.key + " " + $s.key]) vs \($s.value) from \($f.src)"]
            else .bindings[$b.key] = ((.bindings[$b.key] // {}) + {($s.key): $s.value})
               | .prov[$b.key + " " + $s.key] = $f.src end)))
  | .enabled |= unique
' "$FRAGS_JSON")

CONFLICTS=$(printf %s "$MERGED" | jq -r '.conflicts[]?')
if [ -n "$CONFLICTS" ]; then
  echo "merge-manifests: binding conflicts for $NORM -- refusing to guess:" >&2
  printf '%s\n' "$CONFLICTS" >&2
  exit 1
fi

OUT_DIR="$MS_HOME/repos/$SLUG"
mkdir -p "$OUT_DIR"
TMP_OUT=$(mktemp "$OUT_DIR/.skills.jsonc.XXXXXX")
{
  echo "// GENERATED by merge-manifests.sh -- do not hand-edit for keeps;"
  echo "// the next pack install or merge run rewrites this file."
  echo "// repo: $NORM"
  echo "// provenance (binding <- source):"
  printf %s "$MERGED" | jq -r '.prov | to_entries[] | "//   \(.key) <- \(.value)"'
  printf %s "$MERGED" | jq '{version: 1, skills: {enabled: .enabled}, pipelines: .pipelines, bindings: .bindings}'
} > "$TMP_OUT"
strip "$TMP_OUT" | jq -e . > /dev/null || { echo "merge-manifests: emitted invalid JSONC (bug)" >&2; rm -f "$TMP_OUT"; exit 1; }
mv "$TMP_OUT" "$OUT_DIR/skills.jsonc"
echo "wrote $OUT_DIR/skills.jsonc ($DECLARED fragment(s)$( [ -f "$OVR" ] && printf ' + overrides'))"
